# Generated by Django 5.0.3 on 2024-03-24 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipes',
            name='cooking_time',
            field=models.IntegerField(help_text='In minutes'),
        ),
        migrations.AlterField(
            model_name='recipes',
            name='ingredients',
            field=models.CharField(help_text='255 characters max, separated by commas; ex: banana, milk', max_length=255),
        ),
        migrations.AlterField(
            model_name='recipes',
            name='instructions',
            field=models.TextField(help_text='Instructions for making the recipe'),
        ),
        migrations.AlterField(
            model_name='recipes',
            name='name',
            field=models.CharField(help_text='50 characters max', max_length=50),
        ),
    ]
