# Generated by Django 5.0.3 on 2024-03-24 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_alter_recipes_cooking_time_alter_recipes_ingredients_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='recipes',
            new_name='Recipe',
        ),
    ]
