# Generated by Django 5.0.3 on 2024-03-24 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_remove_recipe_ingredients_recipe_difficulty_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='image',
            field=models.ImageField(default='no_image.jpg', upload_to='recipes'),
        ),
    ]
