# Generated by Django 5.0.3 on 2024-03-25 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0007_remove_recipe_instructions_step'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='description',
            field=models.TextField(default='N/A', help_text='Describe what the recipe is about.'),
        ),
    ]
