# Generated by Django 5.0.3 on 2024-03-25 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0008_recipe_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='description',
            field=models.TextField(default='N/A', help_text='Describe what the recipe is about.', max_length=480),
        ),
    ]
