# Generated by Django 5.0.3 on 2024-03-29 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0011_recipe_submitted_by_recipe_submitted_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='difficulty',
            field=models.CharField(default='Unknown', max_length=50),
        ),
    ]
